// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.33.4
// source: internal/plugin/proto/filter.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	FilterService_ApplyRequest_FullMethodName  = "/pluginpb.FilterService/ApplyRequest"
	FilterService_ApplyResponse_FullMethodName = "/pluginpb.FilterService/ApplyResponse"
)

// FilterServiceClient is the client API for FilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilterServiceClient interface {
	ApplyRequest(ctx context.Context, in *ApplyRequestRequest, opts ...grpc.CallOption) (*ApplyRequestResponse, error)
	ApplyResponse(ctx context.Context, in *ApplyResponseRequest, opts ...grpc.CallOption) (*ApplyResponseResponse, error)
}

type filterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterServiceClient(cc grpc.ClientConnInterface) FilterServiceClient {
	return &filterServiceClient{cc}
}

func (c *filterServiceClient) ApplyRequest(ctx context.Context, in *ApplyRequestRequest, opts ...grpc.CallOption) (*ApplyRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyRequestResponse)
	err := c.cc.Invoke(ctx, FilterService_ApplyRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filterServiceClient) ApplyResponse(ctx context.Context, in *ApplyResponseRequest, opts ...grpc.CallOption) (*ApplyResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponseResponse)
	err := c.cc.Invoke(ctx, FilterService_ApplyResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServiceServer is the server API for FilterService service.
// All implementations must embed UnimplementedFilterServiceServer
// for forward compatibility
type FilterServiceServer interface {
	ApplyRequest(context.Context, *ApplyRequestRequest) (*ApplyRequestResponse, error)
	ApplyResponse(context.Context, *ApplyResponseRequest) (*ApplyResponseResponse, error)
	mustEmbedUnimplementedFilterServiceServer()
}

// UnimplementedFilterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilterServiceServer struct {
}

func (UnimplementedFilterServiceServer) ApplyRequest(context.Context, *ApplyRequestRequest) (*ApplyRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyRequest not implemented")
}
func (UnimplementedFilterServiceServer) ApplyResponse(context.Context, *ApplyResponseRequest) (*ApplyResponseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyResponse not implemented")
}
func (UnimplementedFilterServiceServer) mustEmbedUnimplementedFilterServiceServer() {}

// UnsafeFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilterServiceServer will
// result in compilation errors.
type UnsafeFilterServiceServer interface {
	mustEmbedUnimplementedFilterServiceServer()
}

func RegisterFilterServiceServer(s grpc.ServiceRegistrar, srv FilterServiceServer) {
	s.RegisterService(&FilterService_ServiceDesc, srv)
}

func _FilterService_ApplyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServiceServer).ApplyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterService_ApplyRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServiceServer).ApplyRequest(ctx, req.(*ApplyRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilterService_ApplyResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServiceServer).ApplyResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterService_ApplyResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServiceServer).ApplyResponse(ctx, req.(*ApplyResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilterService_ServiceDesc is the grpc.ServiceDesc for FilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginpb.FilterService",
	HandlerType: (*FilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyRequest",
			Handler:    _FilterService_ApplyRequest_Handler,
		},
		{
			MethodName: "ApplyResponse",
			Handler:    _FilterService_ApplyResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugin/proto/filter.proto",
}
